# Home Credit - Credit Risk Model Stability

In this competition, we will be predicting default of clients based on internal and external information that are available for each client.

This dataset contains a large number of tables as a result of utilizing diverse data sources and the varying levels of data aggregation used while preparing the dataset. Below performed EDA is for the previous application clients with depth 1 (File 1, File 2) and depth 2.

Join is performed on the Base table that store the basic information about the observation based on the case_id. This is a unique identification of every loan type.

This notebook contains EDA for following files:

train_applprev_1_0.csv

train_applprev_1_1.csv

train_applprev_2.csv

train_base.csv

Depth values:

depth=0 - These are static features directly tied to a specific case_id.
depth=1 - Each case_id has an associated historical record, indexed by num_group1.
depth=2 - Each case_id has an associated historical record, indexed by both num_group1 and num_group2.

For depth=0 tables, predictors can be directly used as features. However, for tables with depth>0, you may need to employ aggregation functions that will condense the historical records associated with each case_id into a single feature. In case num_group1 or num_group2 stands for person index (this is clear with predictor definitions) the zero index has special meaning. When num_groupN=0 it is the applicant (the person who applied for a loan).

In [1]:
import polars as pl
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

import warnings
warnings.filterwarnings("ignore")

In [2]:
def group_file_data(
    df: pl.DataFrame, 
    num_cols: list[str] = [], 
    date_cols: list[str] = [], 
    cat_cols: list[str] = []
) -> pl.DataFrame:
    '''
    Function to group numerical, date, and categorical columns

    Parameters:
    -----------
    df : Polars DataFrame
    num_cols : List of numerical column names (remember to drop num_group columns)
    date_cols : List of date column names
    cat_cols : List of categorical column names (becomes dummies)
    '''
    
    # Convert date columns
    df_date = df[['case_id'] + date_cols].with_columns([ pl.col(col).str.to_date() for col in date_cols ])

    # One-hot categories
    df_dummies = df[['case_id'] + cat_cols].to_dummies(cat_cols)

    # Num DataFrame
    df_num = df[['case_id'] + num_cols]

    # Date aggs
    date_aggs = [ pl.min(col).name.suffix('_min') for col in date_cols ] +\
                [ pl.max(col).name.suffix('_max') for col in date_cols ] +\
                [ pl.n_unique(col).name.suffix('_distinct') for col in date_cols]
    df_date_grouped = df_date.group_by('case_id').agg(date_aggs)

    # One-hot aggs
    dummy_cols = [ col for col in df_dummies.columns if col != 'case_id']
    dummies_aggs = [ pl.sum(col).name.suffix('_sum') for col in dummy_cols ]
    df_dummies_grouped = df_dummies.group_by('case_id').agg(dummies_aggs)

    # Numerical aggs
    num_aggs = [ pl.min(col).name.suffix('_min') for col in num_cols ] +\
            [ pl.max(col).name.suffix('_max') for col in num_cols ] +\
            [ pl.mean(col).name.suffix('_mean') for col in num_cols ] +\
            [ pl.median(col).name.suffix('_median') for col in num_cols ] +\
            [ pl.sum(col).name.suffix('_sum') for col in num_cols ]
    df_num_grouped = df_num.group_by('case_id').agg(num_aggs)

    # Join DataFrames
    df_joined = df_num_grouped.join(df_date_grouped, on='case_id')
    df_joined = df_joined.join(df_dummies_grouped, on='case_id')

    return df_joined

## Read and inspect the previous application files

In [3]:
#Depth 1
prev_app_0 = pl.read_csv('csv_files/train/train_applprev_1_0.csv')

#Depth 1
prev_app_1 = pl.read_csv('csv_files/train/train_applprev_1_1.csv')

#Depth 2
prev_app_2 = pl.read_csv('csv_files/train/train_applprev_2.csv')

#Base table
base = pl.read_csv('csv_files/train/train_base.csv')

In [29]:
# pandas DataFrame for the inital EDA checks 
prev_app_0_pd = pd.read_csv('csv_files/train/train_applprev_1_0.csv')

prev_app_1_pd = pd.read_csv('csv_files/train/train_applprev_1_1.csv')

prev_app_2_pd = pd.read_csv('csv_files/train/train_applprev_2.csv')

base_pd = pd.read_csv('csv_files/train/train_base.csv')

In [30]:
print(f"Number of Unique Case IDs: {prev_app_0_pd['case_id'].nunique()}")
print(f"Number of Unique Case IDs: {prev_app_1_pd['case_id'].nunique()}")
print(f"Number of Unique Case IDs: {prev_app_2_pd['case_id'].nunique()}")
print(f"Number of Unique Case IDs: {base_pd['case_id'].nunique()}")

Number of Unique Case IDs: 782997
Number of Unique Case IDs: 438525
Number of Unique Case IDs: 1221522
Number of Unique Case IDs: 1526659

### Performing initial checks on the dataset by examining the first five rows, analyzing the data types of the attributes, reviewing summary statistics, and determining the total number of rows and columns.

In [20]:
def perform_eda_checks(df1: prev_app_0_pd, df2: prev_app_1_pd, df3: prev_app_2_pd):
    """
    Perform initial EDA checks (.head(), .info(), .shape, .describe()) on three given dataframes.

    Args:
    df1, df2, df3 (pd.DataFrame): Dataframes to perform the EDA checks on.
    """
    dataframes = [df1, df2, df3]
    for i, df in enumerate(dataframes, start=1):
        print(f"Previous Application {i} EDA Checks\n" + "-" * 20)

        print("\nFirst 5 rows:")
        print(df.head())

        print("\nInfo:")
        print(df.info())

        print("\nShape:")
        print(df.shape)

        print("\nDescription:")
        print(df.describe())

        print("\n" + "=" * 50 + "\n")

In [21]:
perform_eda_checks(prev_app_0_pd, prev_app_1_pd, prev_app_2_pd)

Previous Application 1 EDA Checks
--------------------

First 5 rows:
   case_id  actualdpd_943P  annuity_853A approvaldate_319D  \
0        2             0.0         640.2               NaN
1        2             0.0        1682.4               NaN
2        3             0.0        6140.0               NaN
3        4             0.0        2556.6               NaN
4        5             0.0           NaN               NaN

   byoccupationinc_3656910L cancelreason_3545846M  childnum_21L  \
0                       NaN              a55475b1           0.0
1                       NaN              a55475b1           0.0
2                       NaN           P94_109_143           NaN
3                       NaN             P24_27_36           NaN
4                       NaN           P85_114_140           NaN

  creationdate_885D  credacc_actualbalance_314A  credacc_credlmt_575A  ...  \
0        2013-04-03                         NaN                   0.0  ...
1        2013-04-03                         NaN                   0.0  ...
2        2019-01-07                         NaN                   0.0  ...
3        2019-01-08                         NaN                   0.0  ...
4        2019-01-16                         NaN                   NaN  ...

   num_group1  outstandingdebt_522A pmtnum_8L  postype_4733339M  \
0           0                   NaN      24.0          a55475b1
1           1                   NaN      12.0          a55475b1
2           0                   NaN      12.0          a55475b1
3           0                   NaN      24.0          a55475b1
4           0                   NaN       NaN          a55475b1

   profession_152M rejectreason_755M  rejectreasonclient_4145042M  \
0         a55475b1          a55475b1                     a55475b1
1         a55475b1          a55475b1                     a55475b1
2         a55475b1       P94_109_143                     a55475b1
3         a55475b1          a55475b1                     a55475b1
4         a55475b1          a55475b1                     a55475b1

  revolvingaccount_394A status_219L  tenor_203L
0                   NaN           D        24.0
1                   NaN           D        12.0
2                   NaN           D        12.0
3                   NaN           T        24.0
4                   NaN           T         NaN

[5 rows x 41 columns]

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3887684 entries, 0 to 3887683
Data columns (total 41 columns):
 #   Column                       Dtype
---  ------                       -----
 0   case_id                      int64
 1   actualdpd_943P               float64
 2   annuity_853A                 float64
 3   approvaldate_319D            object
 4   byoccupationinc_3656910L     float64
 5   cancelreason_3545846M        object
 6   childnum_21L                 float64
 7   creationdate_885D            object
 8   credacc_actualbalance_314A   float64
 9   credacc_credlmt_575A         float64
 10  credacc_maxhisbal_375A       float64
 11  credacc_minhisbal_90A        float64
 12  credacc_status_367L          object
 13  credacc_transactions_402L    float64
 14  credamount_590A              float64
 15  credtype_587L                object
 16  currdebt_94A                 float64
 17  dateactivated_425D           object
 18  district_544M                object
 19  downpmt_134A                 float64
 20  dtlastpmt_581D               object
 21  dtlastpmtallstes_3545839D    object
 22  education_1138M              object
 23  employedfrom_700D            object
 24  familystate_726L             object
 25  firstnonzeroinstldate_307D   object
 26  inittransactioncode_279L     object
 27  isbidproduct_390L            object
 28  isdebitcard_527L             object
 29  mainoccupationinc_437A       float64
 30  maxdpdtolerance_577P         float64
 31  num_group1                   int64
 32  outstandingdebt_522A         float64
 33  pmtnum_8L                    float64
 34  postype_4733339M             object
 35  profession_152M              object
 36  rejectreason_755M            object
 37  rejectreasonclient_4145042M  object
 38  revolvingaccount_394A        float64
 39  status_219L                  object
 40  tenor_203L                   float64
dtypes: float64(18), int64(2), object(21)
memory usage: 1.2+ GB
None

Shape:
(3887684, 41)

Description:
            case_id  actualdpd_943P  annuity_853A  byoccupationinc_3656910L  \
count  3.887684e+06    3.885450e+06  3.731833e+06             991660.000000
mean   1.397916e+06    1.056300e-02  3.413166e+03              19796.484030
std    7.601594e+05    3.754277e+00  2.828269e+03              30687.652507
min    2.000000e+00    0.000000e+00  0.000000e+00                  0.000000
25%    1.251506e+06    0.000000e+00  1.710600e+03                  1.000000
50%    1.451959e+06    0.000000e+00  2.761200e+03               5000.000000
75%    1.641585e+06    0.000000e+00  4.396400e+03              30000.000000
max    2.651092e+06    3.676000e+03  1.051302e+05             200000.000000

       childnum_21L  credacc_actualbalance_314A  credacc_credlmt_575A  \
count  1.933791e+06                1.681780e+05          3.768614e+06
mean   8.434702e-01                2.026958e+04          3.254677e+03
std    1.209425e+00                2.600278e+04          1.406135e+04
min    0.000000e+00               -1.140860e+05          0.000000e+00
25%    0.000000e+00                3.030500e+00          0.000000e+00
50%    0.000000e+00                1.258500e+04          0.000000e+00
75%    1.000000e+00                3.044600e+04          0.000000e+00
max    2.000000e+01                2.540730e+06          4.000000e+05

       credacc_maxhisbal_375A  credacc_minhisbal_90A  \
count            1.681780e+05          168178.000000
mean            -3.288887e+03           -6554.784203
std              2.808611e+04           16888.862439
min             -1.961082e+05         -206808.170000
25%              0.000000e+00           -1042.079025
50%              0.000000e+00               0.000000
75%              0.000000e+00               0.000000
max              7.988198e+06          199567.000000

       credacc_transactions_402L  credamount_590A  currdebt_94A  downpmt_134A  \
count              168178.000000     3.764355e+06  2.617307e+06  3.764355e+06
mean                    0.522125     3.865786e+04  5.229101e+03  4.578899e+02
std                     2.951672     3.754434e+04  1.927842e+04  2.697226e+03
min                     0.000000     0.000000e+00  0.000000e+00  0.000000e+00
25%                     0.000000     1.399800e+04  0.000000e+00  0.000000e+00
50%                     0.000000     2.700000e+04  0.000000e+00  0.000000e+00
75%                     0.000000     5.000000e+04  0.000000e+00  0.000000e+00
max                   155.000000     7.153920e+05  5.074297e+05  3.204000e+05

       mainoccupationinc_437A  maxdpdtolerance_577P    num_group1  \
count            3.851072e+06          2.070306e+06  3.887684e+06
mean             4.002969e+04          1.326582e+01  3.910262e+00
std              3.139637e+04          1.348893e+02  4.101353e+00
min              0.000000e+00          0.000000e+00  0.000000e+00
25%              1.800000e+04          0.000000e+00  1.000000e+00
50%              3.400000e+04          0.000000e+00  3.000000e+00
75%              5.200000e+04          1.000000e+00  6.000000e+00
max              1.960000e+05          4.058000e+03  1.900000e+01

       outstandingdebt_522A     pmtnum_8L  revolvingaccount_394A    tenor_203L
count          2.609762e+06  3.574851e+06           1.566510e+05  3.574851e+06
mean           6.994588e+03  1.578210e+01           7.403548e+08  1.578210e+01
std            2.916248e+04  1.046206e+01           5.498686e+07  1.046206e+01
min            0.000000e+00  3.000000e+00           5.403424e+08  3.000000e+00
25%            0.000000e+00  6.000000e+00           7.406884e+08  6.000000e+00
50%            0.000000e+00  1.200000e+01           7.602487e+08  1.200000e+01
75%            0.000000e+00  2.400000e+01           7.607250e+08  2.400000e+01
max            1.210629e+06  6.200000e+01           7.808654e+08  6.200000e+01

==================================================

Previous Application 2 EDA Checks
--------------------

First 5 rows:
   case_id  actualdpd_943P  annuity_853A approvaldate_319D  \
0    40704             0.0     7204.6000               NaN
1    40734             0.0     3870.2000               NaN
2    40737             0.0     2324.4001               NaN
3    40791             0.0     2320.8000               NaN
4    40791             0.0     2541.2000               NaN

   byoccupationinc_3656910L cancelreason_3545846M  childnum_21L  \
0                       NaN           P94_109_143           NaN
1                       NaN           P94_109_143           NaN
2                       1.0              a55475b1           0.0
3                       1.0              a55475b1           0.0
4                       1.0              a55475b1           0.0

  creationdate_885D  credacc_actualbalance_314A  credacc_credlmt_575A  ...  \
0        2018-11-20                         NaN                   0.0  ...
1        2019-12-26                         NaN                   0.0  ...
2        2014-07-17                         NaN                   0.0  ...
3        2014-12-28                         NaN                   0.0  ...
4        2014-12-28                         NaN                   0.0  ...

   num_group1  outstandingdebt_522A pmtnum_8L  postype_4733339M  \
0           0                   NaN      12.0        P46_145_78
1           0                   NaN      18.0       P149_40_170
2           0                   0.0      18.0        P46_145_78
3           1                   0.0      12.0       P60_146_156
4           2                   0.0      24.0      P177_117_192

   profession_152M rejectreason_755M  rejectreasonclient_4145042M  \
0         a55475b1        P198_131_9                  P94_109_143
1         a55475b1        P45_84_106                  P94_109_143
2         a55475b1          a55475b1                     a55475b1
3         a55475b1          a55475b1                     a55475b1
4         a55475b1          a55475b1                     a55475b1

  revolvingaccount_394A status_219L  tenor_203L
0                   NaN           D        12.0
1                   NaN           D        18.0
2                   NaN           D        18.0
3                   NaN           D        12.0
4                   NaN           D        24.0

[5 rows x 41 columns]

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2638295 entries, 0 to 2638294
Data columns (total 41 columns):
 #   Column                       Dtype
---  ------                       -----
 0   case_id                      int64
 1   actualdpd_943P               float64
 2   annuity_853A                 float64
 3   approvaldate_319D            object
 4   byoccupationinc_3656910L     float64
 5   cancelreason_3545846M        object
 6   childnum_21L                 float64
 7   creationdate_885D            object
 8   credacc_actualbalance_314A   float64
 9   credacc_credlmt_575A         float64
 10  credacc_maxhisbal_375A       float64
 11  credacc_minhisbal_90A        float64
 12  credacc_status_367L          object
 13  credacc_transactions_402L    float64
 14  credamount_590A              float64
 15  credtype_587L                object
 16  currdebt_94A                 float64
 17  dateactivated_425D           object
 18  district_544M                object
 19  downpmt_134A                 float64
 20  dtlastpmt_581D               object
 21  dtlastpmtallstes_3545839D    object
 22  education_1138M              object
 23  employedfrom_700D            object
 24  familystate_726L             object
 25  firstnonzeroinstldate_307D   object
 26  inittransactioncode_279L     object
 27  isbidproduct_390L            object
 28  isdebitcard_527L             object
 29  mainoccupationinc_437A       float64
 30  maxdpdtolerance_577P         float64
 31  num_group1                   int64
 32  outstandingdebt_522A         float64
 33  pmtnum_8L                    float64
 34  postype_4733339M             object
 35  profession_152M              object
 36  rejectreason_755M            object
 37  rejectreasonclient_4145042M  object
 38  revolvingaccount_394A        float64
 39  status_219L                  object
 40  tenor_203L                   float64
dtypes: float64(18), int64(2), object(21)
memory usage: 825.3+ MB
None

Shape:
(2638295, 41)

Description:
            case_id  actualdpd_943P  annuity_853A  byoccupationinc_3656910L  \
count  2.638295e+06    2.638029e+06  2.543410e+06             542788.000000
mean   1.482078e+06    2.098536e-02  3.502855e+03              20411.156262
std    8.228526e+05    5.707747e+00  2.963257e+03              30931.990753
min    4.070400e+04    0.000000e+00  0.000000e+00                  0.000000
25%    2.574310e+05    0.000000e+00  1.711600e+03                  1.000000
50%    1.788760e+06    0.000000e+00  2.825800e+03              10000.000000
75%    1.895740e+06    0.000000e+00  4.595600e+03              30000.000000
max    2.703454e+06    4.206000e+03  1.030000e+05             200000.000000

       childnum_21L  credacc_actualbalance_314A  credacc_credlmt_575A  \
count  1.032764e+06                1.518560e+05          2.563233e+06
mean   8.416531e-01                1.605530e+04          3.608608e+03
std    1.238723e+00                2.794865e+04          1.650749e+04
min    0.000000e+00               -1.340084e+05          0.000000e+00
25%    0.000000e+00                0.000000e+00          0.000000e+00
50%    0.000000e+00                1.820000e+02          0.000000e+00
75%    1.000000e+00                2.313600e+04          0.000000e+00
max    2.000000e+01                1.600000e+06          4.000000e+05

       credacc_maxhisbal_375A  credacc_minhisbal_90A  \
count            1.518560e+05          151856.000000
mean            -1.878262e+03           -5670.541866
std              2.960678e+04           18143.378679
min             -2.902651e+05         -350532.600000
25%              0.000000e+00               0.000000
50%              0.000000e+00               0.000000
75%              7.651500e+00               0.000000
max              3.800000e+06          239000.000000

       credacc_transactions_402L  credamount_590A  currdebt_94A  downpmt_134A  \
count              151856.000000     2.559426e+06  1.662160e+06  2.559426e+06
mean                    0.576013     4.298544e+04  5.301262e+03  3.889885e+02
std                     3.226974     4.579684e+04  2.046368e+04  2.614635e+03
min                     0.000000     0.000000e+00  0.000000e+00  0.000000e+00
25%                     0.000000     1.423600e+04  0.000000e+00  0.000000e+00
50%                     0.000000     2.997800e+04  0.000000e+00  0.000000e+00
75%                     0.000000     5.908770e+04  0.000000e+00  0.000000e+00
max                   147.000000     1.000000e+06  4.829808e+05  4.204000e+05

       mainoccupationinc_437A  maxdpdtolerance_577P    num_group1  \
count            2.572924e+06          1.359969e+06  2.638295e+06
mean             4.304612e+04          1.678875e+01  4.613016e+00
std              3.255007e+04          1.581358e+02  4.485515e+00
min              0.000000e+00          0.000000e+00  0.000000e+00
25%              2.000000e+04          0.000000e+00  1.000000e+00
50%              3.700000e+04          0.000000e+00  3.000000e+00
75%              5.800000e+04          1.000000e+00  7.000000e+00
max              1.996000e+05          4.362000e+03  1.900000e+01

       outstandingdebt_522A     pmtnum_8L  revolvingaccount_394A    tenor_203L
count          1.657949e+06  2.399308e+06           1.400990e+05  2.399308e+06
mean           7.097728e+03  1.685803e+01           7.619334e+08  1.685803e+01
std            3.087146e+04  1.125159e+01           4.755881e+07  1.125159e+01
min            0.000000e+00  3.000000e+00           5.403423e+08  3.000000e+00
25%            0.000000e+00  9.000000e+00           7.601635e+08  9.000000e+00
50%            0.000000e+00  1.200000e+01           7.803115e+08  1.200000e+01
75%            0.000000e+00  2.400000e+01           7.807900e+08  2.400000e+01
max            1.029393e+06  6.300000e+01           8.006087e+08  6.300000e+01

==================================================

Previous Application 3 EDA Checks
--------------------

First 5 rows:
   case_id cacccardblochreas_147M   conts_type_509L credacc_cards_status_52L  \
0        2                    NaN    PRIMARY_MOBILE                      NaN
1        2                    NaN  EMPLOYMENT_PHONE                      NaN
2        2                    NaN    PRIMARY_MOBILE                      NaN
3        2                    NaN  EMPLOYMENT_PHONE                      NaN
4        3                    NaN             PHONE                      NaN

   num_group1  num_group2
0           0           0
1           0           1
2           1           0
3           1           1
4           0           0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14075487 entries, 0 to 14075486
Data columns (total 6 columns):
 #   Column                    Dtype
---  ------                    -----
 0   case_id                   int64
 1   cacccardblochreas_147M    object
 2   conts_type_509L           object
 3   credacc_cards_status_52L  object
 4   num_group1                int64
 5   num_group2                int64
dtypes: int64(3), object(3)
memory usage: 644.3+ MB
None

Shape:
(14075487, 6)

Description:
            case_id    num_group1    num_group2
count  1.407549e+07  1.407549e+07  1.407549e+07
mean   1.454198e+06  4.551473e+00  7.403148e-01
std    7.875084e+05  4.390422e+00  8.025843e-01
min    2.000000e+00  0.000000e+00  0.000000e+00
25%    1.237440e+06  1.000000e+00  0.000000e+00
50%    1.575626e+06  3.000000e+00  1.000000e+00
75%    1.861301e+06  7.000000e+00  1.000000e+00
max    2.703454e+06  1.900000e+01  1.100000e+01

==================================================

### Aggregation and Merge to the Base table

In [10]:
# Aggregation functions for numerical columns
numerical_agg_funcs = {
    'min': 'min',
    'max': 'max',
    'mean': 'mean',
    'median': 'median',
    'sum': 'sum'
}

# Aggregation functions for categorical columns
categorical_agg_funcs = {
    'mode': lambda x: x.mode().iloc[0],  # Mode
    'one_hot_encoding': lambda x: x.sum()  # One-hot encoding with sum of counts
}

# Aggregation functions for date columns
date_agg_funcs = {
    'min': 'min',
    'max': 'max',
    'distinct_count': 'nunique'  # Count of distinct values
}

### Below code snippet to test the aggregation and merging of 1 feature in the dataset

In [13]:
df = prev_app_1

# Select at most one date column
date_cols = [col for col in df.columns if 'dat' in col and df[col].dtype == pl.String][:1]

# Select at most one categorical column, excluding already selected date columns
cat_cols = [col for col in df.columns if col not in date_cols and df[col].dtype == pl.String][:1]

# Define ignored columns
ignore_cols = ['case_id', 'num_group1']

# Select at most one numerical column, excluding already selected date and categorical columns
num_cols = [col for col in df.columns 
            if col not in date_cols + cat_cols + ignore_cols 
            and df[col].dtype != pl.String][:1]

# Ensure we have only three columns in total
selected_cols = date_cols + cat_cols + num_cols[:max(3 - len(date_cols + cat_cols), 0)]

# Group data using only the selected columns
df_prev_app_1_agg = group_file_data(df, num_cols, date_cols, cat_cols)

In [16]:
df_prev_app_1_agg.head()

shape: (5, 82)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ case_id ┆ actualdpd_ ┆ actualdpd ┆ actualdpd ┆ … ┆ cancelrea ┆ cancelrea ┆ cancelrea ┆ cancelrea │
│ ---     ┆ 943P_min   ┆ _943P_max ┆ _943P_mea ┆   ┆ son_35458 ┆ son_35458 ┆ son_35458 ┆ son_35458 │
│ i64     ┆ ---        ┆ ---       ┆ n         ┆   ┆ 46M_P98_3 ┆ 46M_P99_9 ┆ 46M_P9_82 ┆ 46M_a5547 │
│         ┆ f64        ┆ f64       ┆ ---       ┆   ┆ 8_170…    ┆ 8_113…    ┆ _76_s…    ┆ 5b1_s…    │
│         ┆            ┆           ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆ i64       ┆ i64       ┆ i64       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 222314  ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 2         │
│ 969122  ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 1         ┆ 0         ┆ 0         │
│ 1773802 ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 3         │
│ 2672892 ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 3         │
│ 51683   ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ 1         │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Preview Application: Depth 1, File 1

In [ ]:
df = prev_app_0
# Date columns
date_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i].__contains__('dat')) and (df.dtypes[i] == pl.String) ]

# Categorical columns
cat_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i] not in date_cols) and (df.dtypes[i] == pl.String) ]

# Numerical columns
ignore_cols = ['case_id', 'num_group1']
num_cols = [ 
    df.columns[i] for i in range(len(df.columns)) 
    if (df.columns[i] not in date_cols) and (df.columns[i] not in cat_cols) and (df.columns[i] not in ignore_cols)
]

# Group data
df_prev_app_0_agg = group_file_data(df, num_cols, date_cols, cat_cols)

### Preview Application: Depth 1, File 2

In [ ]:
df = prev_app_1
# Date columns
date_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i].__contains__('dat')) and (df.dtypes[i] == pl.String) ]

# Categorical columns
cat_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i] not in date_cols) and (df.dtypes[i] == pl.String) ]

# Numerical columns
ignore_cols = ['case_id', 'num_group1']
num_cols = [ 
    df.columns[i] for i in range(len(df.columns)) 
    if (df.columns[i] not in date_cols) and (df.columns[i] not in cat_cols) and (df.columns[i] not in ignore_cols)
]

# Group data
df_prev_app_1_agg = group_file_data(df, num_cols, date_cols, cat_cols)

### Preview Application: Depth 2

In [ ]:
df = prev_app_2
# Date columns
date_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i].__contains__('dat')) and (df.dtypes[i] == pl.String) ]

# Categorical columns
cat_cols = [ df.columns[i] for i in range(len(df.columns)) if (df.columns[i] not in date_cols) and (df.dtypes[i] == pl.String) ]

# Numerical columns
ignore_cols = ['case_id', 'num_group1', 'num_group2']
num_cols = [ 
    df.columns[i] for i in range(len(df.columns)) 
    if (df.columns[i] not in date_cols) and (df.columns[i] not in cat_cols) and (df.columns[i] not in ignore_cols)
]

# Group data
df_prev_app_2_agg = group_file_data(df, num_cols, date_cols, cat_cols)

### Join all the tables to Base table

In [ ]:
# Join the previous application tables to the base table
prev_app_base = base.join(
    df_prev_app_0_agg, how="left", on="case_id"
).join(
    df_prev_app_1_agg, how="left", on="case_id"
).join(
    df_prev_app_2_agg, how="left", on="case_id"
)